# Dev Environment Profile Configuration
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

adapter:
  bank-bic: PMRBSOMM
  certs:
    dir: ./certs
    ca-cert-file: chain.pem
    bank-cert-file: certificate.pem
    private-key-file: private.pem
    private-key-passphrase: ""
    strict-startup-check: true
  signature:
    algorithm: SHA256withRSA
    canonicalization: EXCLUSIVE
    xades-enabled: true
    xades-namespace: http://uri.etsi.org/01903/v1.3.2#
